/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.NhanVienDAO;
import Controller.SanPhamDAO;
import Model.NhanVien;
import Model.SanPham;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trong
 */
public class Sua_San_Pham extends javax.swing.JDialog {
    private int MaSP;
  
    private DefaultTableModel tableModel;
    private QuanLy_UI quanli_ui;
    public void receiveData(int ma){
        this.MaSP = ma;
    };
    public Sua_San_Pham(int ma, JFrame parent, DefaultTableModel tableModel) {
        super(parent, "Thêm Nhân Viên mới", true);
        this.MaSP = ma;
        this.tableModel = tableModel;
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        quanli_ui = (QuanLy_UI) parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        info_panel = new javax.swing.JPanel();
        HoTen_Label = new javax.swing.JLabel();
        SDT_Label = new javax.swing.JLabel();
        Tuoi_Label = new javax.swing.JLabel();
        TenSP = new javax.swing.JTextField();
        soluong = new javax.swing.JTextField();
        gia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cb_loai = new javax.swing.JComboBox<>();
        btn_panel = new javax.swing.JPanel();
        btn_sua = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sửa Thông Tin Sản Phẩm");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        HoTen_Label.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        HoTen_Label.setText("Tên Sản phẩm");

        SDT_Label.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        SDT_Label.setText("Tồn kho");

        Tuoi_Label.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Tuoi_Label.setText("Đơn giá");

        TenSP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TenSP.setMaximumSize(new java.awt.Dimension(2147483647, 40));

        soluong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        gia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Loại Sản phẩm");

        cb_loai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cb_loai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout info_panelLayout = new javax.swing.GroupLayout(info_panel);
        info_panel.setLayout(info_panelLayout);
        info_panelLayout.setHorizontalGroup(
            info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info_panelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tuoi_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SDT_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HoTen_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TenSP, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(soluong, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(gia, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(cb_loai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        info_panelLayout.setVerticalGroup(
            info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TenSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(info_panelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(HoTen_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_loai)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(soluong)
                    .addComponent(SDT_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gia)
                    .addComponent(Tuoi_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btn_sua.setBackground(new java.awt.Color(153, 255, 255));
        btn_sua.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_reset.setBackground(new java.awt.Color(255, 51, 51));
        btn_reset.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_reset.setText("Huy");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btn_panelLayout = new javax.swing.GroupLayout(btn_panel);
        btn_panel.setLayout(btn_panelLayout);
        btn_panelLayout.setHorizontalGroup(
            btn_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_panelLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        btn_panelLayout.setVerticalGroup(
            btn_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("SỬA THÔNG TIN SẢN PHẨM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(info_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(info_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        String tensp = TenSP.getText();
        if(tensp == null){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập Tên Sản Phẩm!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        String loai = (String) cb_loai.getSelectedItem();
        
        int giasp, sl;
        if(gia.getText().trim().isEmpty()){
            giasp = 0;
        }else{
            giasp = Integer.parseInt(gia.getText());
        }
        
        if(soluong.getText().trim().isEmpty()){
            sl = 0;
        }else{
            sl = Integer.parseInt(soluong.getText());
        }
        
        SanPham SP = new SanPham(this.MaSP,tensp, loai, giasp, sl);
        
        boolean updated = SanPhamDAO.EditSP(SP);
        if(updated){
            JOptionPane.showMessageDialog(null, "Thông tin sản phẩm đã được cập nhập", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            for (int i = 0; i < tableModel.getRowCount(); i++) {
                int maSP = (int) tableModel.getValueAt(i, 0); 
                if (maSP == this.MaSP) {
                    // Cập nhật thông tin cho hàng tương ứng
                    tableModel.setValueAt(tensp, i, 1);
                    tableModel.setValueAt(loai, i, 2);
                    tableModel.setValueAt(giasp, i, 3);
                    tableModel.setValueAt(sl, i, 4);
                    break;
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Cập Nhập Thất Bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        dispose();
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        DSDMSP();
        EditSPShow();
    }//GEN-LAST:event_formComponentShown
    public void EditSPShow(){
        SanPham SP =SanPhamDAO.ShowSPbyMa(this.MaSP);
        TenSP.setText(SP.getTenSP());
        gia.setText(String.valueOf(SP.getGia()));
        soluong.setText(String.valueOf(SP.getSoLuong()));
        
        cb_loai.setSelectedItem(SP.getLoaiSP());
    }
    public void DSDMSP() {
        List<Object[]> dataList = SanPhamDAO.ListDMSP(); 
        List<String> DSDMSP_name = new ArrayList<>();
        for (Object[] data : dataList) {
            if (data.length > 1 && data[1] != null) {
                DSDMSP_name.add((String) data[1]);
            }
        }

        // Sử dụng phương thức toArray(T[] a) với kiểu mảng cụ thể
        String[] list = DSDMSP_name.toArray(new String[0]);

        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>(list);
        cb_loai.setModel(comboBoxModel);
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HoTen_Label;
    private javax.swing.JLabel SDT_Label;
    private javax.swing.JTextField TenSP;
    private javax.swing.JLabel Tuoi_Label;
    private javax.swing.JPanel btn_panel;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_sua;
    private javax.swing.JComboBox<String> cb_loai;
    private javax.swing.JTextField gia;
    private javax.swing.JPanel info_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField soluong;
    // End of variables declaration//GEN-END:variables
}
